# Assignment 3

Task 1:


1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [36]:
def divideFunction():
        try:
            val1 = int(input("Please enter Numerator integer: "))
            val2 = int(input("Please enter Denominator integer: "))
            try:
                val3= val1/val2
                print("Value of '" + str(val1) +"/"+str(val2) + "' is: "+ str(val3))
            except:
                print("Looks like you entered denominator as zero" )
        except:
            print("Looks like you did not enter an integer!" )
  

In [37]:
divideFunction()


Please enter Numerator integer: 8
Please enter Denominator integer: 3
Value of '8/3' is: 2.6666666666666665


2. Implement a Python program to generate all sentences where 
subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].



In [52]:
#def generateSentence():
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


In [57]:
result =(  i +" " + j +" " + k for i in subjects for j in verbs for k in objects)
for abc in result: print(abc)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Task 2:

1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [71]:
import numpy as np

x= np.array([1,2,3,4,5])
np.vander(x,increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [72]:
np.vander(x,increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [70]:
N =8
np.column_stack([x**(N-i-1) for i in range (N) ])

array([[    1,     1,     1,     1,     1,     1,     1,     1],
       [  128,    64,    32,    16,     8,     4,     2,     1],
       [ 2187,   729,   243,    81,    27,     9,     3,     1],
       [16384,  4096,  1024,   256,    64,    16,     4,     1],
       [78125, 15625,  3125,   625,   125,    25,     5,     1]],
      dtype=int32)